spring:
  config:
    activate:
      on-profile: "kafka"
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: ${PRODUCT_GROUP_ID}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json:
          trusted.packages: "com.irum.orderservice.domain.order.event.*"
          type.mapping: |
            orderFailedEvent: com.irum.productservice.domain.product.event.OrderFailedEvent


    partition: ${NUM_OF_PARTITION}
    replica: ${NUM_OF_REPLICA}
    topics:
      order-failed: ${ORDER_FAILED_TOPIC_NAME}

logging:
  level:
    com.adjh.springbootkafka: DEBUG
    org:
      apache.kafka: INFO
      springframework.kafka: INFO
