#!/bin/bash

BASE_DIR="../src/main/java/com/irum/productservice/domain"
TARGET_SUBDIRS=("application" "infrastructure" "presentation")

echo ".gitkeep 파일 삭제"

find "$BASE_DIR" -name ".gitkeep" -delete

for MODULE_DIR in $(find "$BASE_DIR" -mindepth 1 -maxdepth 1 -type d ); do

  echo "$MODULE_DIR"

  for SUB_DIR_NAME in "${TARGET_SUBDIRS[@]}"; do

    SOURCE_PATH="$MODULE_DIR/$SUB_DIR_NAME"

    if [ -d "$SOURCE_PATH" ]; then
      echo "$SUB_DIR_NAME 내부 파일 이동: $SOURCE_PATH -> $MODULE_DIR"
      mv -n "$SOURCE_PATH"/* "$MODULE_DIR"

      if [ -z "$(ls -A "$SOURCE_PATH")" ]; then
        rmdir "$SOURCE_PATH"
        echo "빈 폴더 삭제: $SOURCE_PATH"
      else
        echo "$SOURCE_PATH 폴더 비어있지 않음"

      fi
    fi

  done

done